### PR TITLE
Accessibility

### PR DESCRIPTION
**Pull request by aeon9300**
### Accessbility Issues 

- Page titles: ◀️  : small_blue_triangle_left: : No issues found :heavy_check_mark:
- Image text alternatives: ◀️  Add alt meaningful alt text to images in html file
        - [Edited alt's lines 50, 73, 77, 81, 85, 89, 99, 103, 217, 259, 289, 293, 297,301,305](https://github.com/aeon9300/Portfolio-setup-and-mobile-version-skeleton-2/pull/13/files/6563b71a5cbc870077b4a9b79fcb3240efd54124#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R50-R305)

- Text headings: ◀️  No issues found :heavy_check_mark:
- Color contrast: ◀️  No issues found :heavy_check_mark:
- Resize: ◀️ No issues found :heavy_check_mark:
- Interaction: ◀️  Enable navigation links to jump to the exact section on the website
        - [Edited lines 37-40, 99, 217, 259](https://github.com/aeon9300/Portfolio-setup-and-mobile-version-skeleton-2/pull/13/files/6563b71a5cbc870077b4a9b79fcb3240efd54124#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R50-R305)

- Moving content: ◀️  No issues found :heavy_check_mark:
- Multimedia: ◀️ No issues found :heavy_check_mark:
- The basic structure of the page: ◀️  No issues found :heavy_check_mark: 
😄

### CODE REVIEW

**Review by Cathella — CHANGES_REQUESTED** [review]
## 🟡 Status: Changes Requested 🛑 

### Hi @team 👋🏻, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️

- [ ]  According to the requirements, you should have a report in your Pull Request that must include the following 👇🏻 

image

Please kindly take a look at the summarized report below - and see how best you can come up with yours 👇🏻 

image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by aeon9300 — COMMENTED** [review]
Add alt text to image in portfolio

**Comment by aeon9300** [comment]
Accessbility Issues
Page titles: ◀️ : small_blue_triangle_left: : No issues found ✔️

Image text alternatives: ◀️ Add alt meaningful alt text to images in html file
- Edited alt's lines 50, 73, 77, 81, 85, 89, 99, 103, 217, 259, 289, 293, 297,301,305

Text headings: ◀️ No issues found ✔️

Color contrast: ◀️ No issues found ✔️

Resize: ◀️ No issues found ✔️

Interaction: ◀️ Enable navigation links to jump to the exact section on the website
- Edited lines 37-40, 99, 217, 259

Moving content: ◀️ No issues found ✔️

Multimedia: ◀️ No issues found ✔️

The basic structure of the page: ◀️ No issues found ✔️

**Comment by aeon9300** [comment]
### Accessbility Issues 

- Page titles: ◀️  : small_blue_triangle_left: : No issues found :heavy_check_mark:
- Image text alternatives: ◀️  Add alt meaningful alt text to images in html file
        - [Edited alt's lines 50, 73, 77, 81, 85, 89, 99, 103, 217, 259, 289, 293, 297,301,305](https://github.com/aeon9300/Portfolio-setup-and-mobile-version-skeleton-2/pull/13/files/6563b71a5cbc870077b4a9b79fcb3240efd54124#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R50-R305)

- Text headings: ◀️  No issues found :heavy_check_mark:
- Color contrast: ◀️  No issues found :heavy_check_mark:
- Resize: ◀️ No issues found :heavy_check_mark:
- Interaction: ◀️  Enable navigation links to jump to the exact section on the website
        - [Edited lines 37-40, 99, 217, 259](https://github.com/aeon9300/Portfolio-setup-and-mobile-version-skeleton-2/pull/13/files/6563b71a5cbc870077b4a9b79fcb3240efd54124#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R50-R305)

- Moving content: ◀️  No issues found :heavy_check_mark:
- Multimedia: ◀️ No issues found :heavy_check_mark:
- The basic structure of the page: ◀️  No issues found :heavy_check_mark: 
😄

**Pull request merged**
